name = "huff_ada"
description = "Huffman encoder"
version = "0.1.0-dev"

authors = ["Lars T Hansen"]
maintainers = ["Lars T Hansen <lars.thomas.hansen@knowit.no>"]
maintainers-logins = ["lars-t-hansen"]

executables = ["huff_ada"]

[build-switches]
"*".runtime_checks = ["-gnata"]
"*".style_checks = ["-gnatya", "-gnatyA", "-gnatyB", "-gnaty-d", "-gnatye", "-gnatyf", "-gnatyh", "-gnatyi", "-gnatyI", "-gnatyk", "-gnatyl", "-gnatyn", "-gnatyO", "-gnatyp", "-gnatyr", "-gnatyS", "-gnatyx"]